"""Add Visit model and link relationships

Revision ID: f406ce4aefbc
Revises: 7fb634d48906
Create Date: 2025-10-04 19:45:06.139338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f406ce4aefbc'
down_revision = '7fb634d48906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    op.drop_table('visit')
    # ### end Alembic commands ###
